base=category_editor
dir=postprocessors
script=$(dir)/$(base)
conf=$(script).conf
status=status.csum
sha=m.sha
version=m.version
xmltv=/home/mythtv/.shepherd/output.xmltv

all:		$(status)

$(status):	$(version) $(sha)
		(echo postprocessor `basename $(script)` `cat $(version)` `sed 's/ .*//' $(sha)`; echo END) > $(status)
		cat $(status)

$(sha):		$(conf) $(script)
		shasum $(conf) $(script) | diff - $(state) > /dev/null 2>&1 || shasum $(conf) $(script) > $(sha)

$(version):	$(script)
		perl -n -e 'if (/^my .version = "(\d+\.\d+)";/){print $$1, "\n";exit;}' $(script) > $(version)

$(script):	$(conf)
		perl -p -e 'if (/(^my .version = "\d+\.)(\d+)/){$$v=$$2;$$v++;s//$$1$$v/;}' -i.bak $(script)

# Test compile time and run time syntactic validity of the variations of
# rulesets generated by various selectors, as this is the hardest to debug,
# so try not to ship something that is broken while being easily testable.
test:		$(script)
		for t in `sed '/^#[A-Z][A-Z0-9]*#/!d;s/[ \t].*//' $(script)|tr '#' '\012'|sort -u|sed '/^$$/d'`; do echo -n "$$t "; if $(script) --output=none --select=$$t --debug $(xmltv) > /dev/null 2>&1; then echo ok; else echo fail; fi; done
